import{a as h,S as b,i as l}from"./assets/vendor-DbKZXEqC.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const p of o.addedNodes)p.tagName==="LINK"&&p.rel==="modulepreload"&&i(p)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();h.defaults.baseURL="https://pixabay.com";const m=async(t,r)=>{const s={params:{key:"45491471-a9703abbe87dc4841cd0b555c",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}};return await h.get("/api/",s)},y=t=>`
  <li class="gallery-card">
    <a class="gallery_link" href ="${t.largeImageURL}">
    <img class="gallery-img" src="${t.webformatURL}" alt="${t.tags}" title="${t.tags}"/>
    <ul class ="image-details">
    <p>Likes<span>${t.likes}</span></p>
    <p>Views<span>${t.views}</span></p>
    <p>Commets<span>${t.comments}</span></p>
    <p>Downloads<span>${t.downloads}</span></p>
    </ul>
    </a>
  </li>
  `,S=new b(".js-gallery a",{animationSpeed:250}),u=document.querySelector(".js-search-form"),n=document.querySelector(".js-gallery"),f=document.querySelector(".js-loader"),d=document.querySelector(".js-load-more"),g=()=>u.reset(),w=()=>{f.classList.remove("is-hidden")};let a=1,c="",L=0;const M=async t=>{t.preventDefault(),c=u.elements.user_query.value,w(),console.log(c),a=1;const r=await m(c,a);try{if(r.data.hits.length===0){l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),n.innerHTML="",g();return}n.innerHTML="";const s=r.data.hits.map(e=>y(e)).join("");n.insertAdjacentHTML("beforeend",s),g(),S.refresh(),L=n.querySelector("li").getBoundingClientRect().height,d.classList.remove("is-hidden"),Math.ceil(r.data.totalHits/15)===a&&(l.info({message:"It`s all images for your request!",position:"topRight"}),d.classList.add("is-hidden"))}catch(s){console.log(s),l.error({message:"Sorry, something get wrong. Try again later!",position:"topRight"})}f.classList.add("is-hidden")},q=async t=>{const r=await m(c,a);try{a++;const s=r.data.hits.map(i=>y(i)).join("");n.insertAdjacentHTML("beforeend",s),scrollBy({top:L*2,behavior:"smooth"}),Math.ceil(r.data.totalHits/15)===a&&(l.info({message:"It`s all images for your request!",position:"topRight"}),d.classList.add("is-hidden"))}catch(s){console.log(s),l.error({message:"Sorry, something get wrong. Try again later!",position:"topRight"})}};u.addEventListener("submit",M);d.addEventListener("click",q);
//# sourceMappingURL=index.js.map
