import{a as h,S,i as a}from"./assets/vendor-DbKZXEqC.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const p of o.addedNodes)p.tagName==="LINK"&&p.rel==="modulepreload"&&n(p)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();h.defaults.baseURL="https://pixabay.com";const m=async(t,r)=>{const s={params:{key:"45491471-a9703abbe87dc4841cd0b555c",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}};return await h.get("/api/",s)},y=t=>`
  <li class="gallery-card">
    <a class="gallery_link" href ="${t.largeImageURL}">
    <img class="gallery-img" src="${t.webformatURL}" alt="${t.tags}" title="${t.tags}"/>
    <ul class ="image-details">
    <p>Likes<span>${t.likes}</span></p>
    <p>Views<span>${t.views}</span></p>
    <p>Commets<span>${t.comments}</span></p>
    <p>Downloads<span>${t.downloads}</span></p>
    </ul>
    </a>
  </li>
  `,f=new S(".js-gallery a",{animationSpeed:250}),u=document.querySelector(".js-search-form"),l=document.querySelector(".js-gallery"),L=document.querySelector(".js-loader"),d=document.querySelector(".js-load-more"),g=()=>u.reset(),w=()=>{L.classList.remove("is-hidden")};let i=1,c="",b=0;const q=async t=>{if(t.preventDefault(),console.log(c),c=u.elements.user_query.value,c===""){a.warning({message:"Please, enter your request in the field!",position:"topRight"});return}w(),i=1;const r=await m(c,i);try{if(r.data.hits.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),l.innerHTML="",g();return}l.innerHTML="";const s=r.data.hits.map(e=>y(e)).join("");l.insertAdjacentHTML("beforeend",s),g(),f.refresh(),b=l.querySelector("li").getBoundingClientRect().height,d.classList.remove("is-hidden"),Math.ceil(r.data.totalHits/15)===i&&(a.info({message:"It`s all images for your request!",position:"topRight"}),d.classList.add("is-hidden"))}catch(s){console.log(s),a.error({message:"Sorry, something get wrong. Try again later!",position:"topRight"})}L.classList.add("is-hidden")},M=async t=>{const r=await m(c,i);try{i++;const s=r.data.hits.map(n=>y(n)).join("");l.insertAdjacentHTML("beforeend",s),f.refresh(),scrollBy({top:b*2,behavior:"smooth"}),Math.ceil(r.data.totalHits/15)===i&&(a.info({message:"It`s all images for your request!",position:"topRight"}),d.classList.add("is-hidden"))}catch(s){console.log(s),a.error({message:"Sorry, something get wrong. Try again later!",position:"topRight"})}};u.addEventListener("submit",q);d.addEventListener("click",M);
//# sourceMappingURL=index.js.map
