import{a as h,S as b,i as l}from"./assets/vendor-DbKZXEqC.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const d of a.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&i(d)}).observe(document,{childList:!0,subtree:!0});function s(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function i(e){if(e.ep)return;e.ep=!0;const a=s(e);fetch(e.href,a)}})();h.defaults.baseURL="https://pixabay.com";const m=(t,r)=>{const s={params:{key:"45491471-a9703abbe87dc4841cd0b555c",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}};return h.get("/api/",s)},y=t=>`
  <li class="gallery-card">
    <a class="gallery_link" href ="${t.largeImageURL}">
    <img class="gallery-img" src="${t.webformatURL}" alt="${t.tags}" title="${t.tags}"/>
    <ul class ="image-details">
    <p>Likes<span>${t.likes}</span></p>
    <p>Views<span>${t.views}</span></p>
    <p>Commets<span>${t.comments}</span></p>
    <p>Downloads<span>${t.downloads}</span></p>
    </ul>
    </a>
  </li>
  `,S=new b(".js-gallery a",{animationSpeed:250}),u=document.querySelector(".js-search-form"),n=document.querySelector(".js-gallery"),f=document.querySelector(".js-loader"),c=document.querySelector(".js-load-more"),g=()=>u.reset(),M=()=>{f.classList.remove("is-hidden")};let o=1,p="",L=0;const q=async t=>{t.preventDefault(),M(),p=u.elements.user_query.value,o=32;const r=await m(p,o);try{if(r.data.hits.length===0){l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),n.innerHTML="",g();return}n.innerHTML="";const s=r.data.hits.map(e=>y(e)).join("");n.insertAdjacentHTML("beforeend",s),g(),S.refresh(),L=n.querySelector("li").getBoundingClientRect().height,c.classList.remove("is-hidden"),Math.ceil(r.data.totalHits/15)===o&&(l.info({message:"It`s all images for your request!",position:"topRight"}),c.classList.add("is-hidden"))}catch(s){console.log(s),l.error({message:"Sorry, something get wrong. Try again later!",position:"topRight"})}f.classList.add("is-hidden")},v=async t=>{const r=await m(p,o);try{o+=1;const s=r.data.hits.map(i=>y(i)).join("");n.insertAdjacentHTML("beforeend",s),scrollBy({top:L*2,behavior:"smooth"}),Math.ceil(r.data.totalHits/15)===o&&(l.info({message:"It`s all images for your request!",position:"topRight"}),c.classList.add("is-hidden"))}catch(s){console.log(s)}};u.addEventListener("submit",q);c.addEventListener("click",v);
//# sourceMappingURL=index.js.map
